### ISSUE TITLE
Infinite loop if replacement contains the search text

### ISSUE THREAD

**Issue by TIAcode** [hoehermann/pypdf_strreplace#1]
Replacing "ABCD" with "1ABCD" gets stuck in infinite loop at first match as it keeps finding ABCD over and over again. Made a terrible quick fix for it and it did the job well after that.

**Comment by hoehermann** [comment]
Thank you for the report. Good catch. Nice to hear you found a workaround. Thank you for letting me know. :)

That is a side-effect of my awful custom `str.find(…)` implementation. I should probably assert that `start` and `end` increase strictly monotonically (with `start` being after the `end` of the previous iteration) in [replace_text](https://github.com/hoehermann/pypdf_strreplace/blob/ed0f5197c3f2c8d3d1dfad85afcdc8ebb7975d8d/pypdf_strreplace.py#L233). Or even better: Implement mapping to a plain string, then I can also support searching with regular expressions.

Unfortunately, I currently do not have enough spare time for developing this tool. I hope one day I can come back to it.

**Comment by hoehermann** [comment]
This is working now.
