### ISSUE TITLE
The text was replaced but the script wrote over it

### ISSUE THREAD

**Issue by lganibenq** [hoehermann/pypdf_strreplace#2]
![image](https://github.com/hoehermann/pypdf_strreplace/assets/159480738/eac68b02-ba2c-4213-a303-afb2e3efa2fd)
(I dont have modify anything in the script)

**Comment by hoehermann** [comment]
Thank you for the report.

Unfortunately, this is a common problem. I guess, in your PDF, the text is positioned very explicitly. A human designer (or a layout engine) decided where each character should be. Can you share the original PDF with me? In case I can work on the project, it is nice to have the specific data to develop against.

I could probably make the tool smarter (e.g. shift text to the right), but PDF is a complex format and there are many things I would need to consider. Even if I would make the tool smarter, I could only handle a single line. Changing a paragraph (with wrapped text or even hyphenation) is definitely out of scope for a free tool. For that, you need to get one of the "big guns":

* [Master PDF Editor](https://code-industry.net/masterpdfeditor/)
* [PDF Studio Pro](https://www.qoppa.com/pdfstudio/)
* [Adobe Acrobat Pro](https://www.adobe.com/de/acrobat/acrobat-pro.html)
* [unipdf-cli](https://github.com/unidoc/unipdf-cli) (unipdf) _CLI_

If you want to stick to this tool, you might try some of the workarounds:

* Change the wording of the replacement text so it is of similar length
* Replace the entire line of text

Try a different free tool: 

* [PDF4QT](https://github.com/JakubMelka/PDF4QT) _GUI_
* [pdf-redactor](https://github.com/JoshData/pdf-redactor) (pdfrw)
* [borb](https://github.com/jorisschellekens/borb-examples?tab=readme-ov-file#77-replacing-text-in-an-existing-pdf)

Try building your own tool based on existing approaches with other libraries:

* [fitz](https://stackoverflow.com/questions/75387339/how-can-i-edit-modify-replace-text-in-an-existing-pdf-file)
* [pyMuPDF](https://github.com/pymupdf/PyMuPDF/discussions/1674)

I am grateful this tool is being appreciated. Unfortunately, I do currently not have enough spare time for further development. Contributions are welcome. :)

**Comment by hoehermann** [comment]
Without the sample document, there is not much I can do.
