### ISSUE TITLE
Replacement is only executed until first occurrence of end character

### ISSUE THREAD

**Issue by JJK96** [hoehermann/pypdf_strreplace#5]
Example:

You try to replace the string "ABCDB" with "AAAAA".

result:

"AAAAACDB"

This is because in `search_in_mappings`, start = "A" and end = "B". Then in PDFOperationTJ.replace_text,`end = self.operands[0].index(end)`, which will result in the first occurrence of B. Then the replacement will be between the first occurrence of A and the first occurrence of B.

I'm not sure how to fix it, but I will make an attempt. If you have an idea in the mean time, let me know!

**Comment by hoehermann** [comment]
I spent way more time on this project than I am willing to admit in public. I totally overhauled how the search is done. Searching is now done by regular expression. The code is rather messy and full of debug output. Can you tell me if https://github.com/hoehermann/pypdf_strreplace/tree/debug-gui works okay for you?

**Comment by JJK96** [comment]
Thank you for the time you put into it!

The first problem I run into is that the `--search` parameter is no longer optional to simply list all strings.
The replacements work fine though! Also with a simple regex.

**Comment by hoehermann** [comment]
Thank you for the feed-back.

Good point. I want to re-enable the text listing feature next week.

**Comment by hoehermann** [comment]
I think, all original features are now present in the overhauled version. I even fixed #1 along the way. In case something is missing, feel free to re-open this issue or post a new one.

**Comment by JJK96** [comment]
Thank you!
